version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: movie_trends
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: movie_user
      MYSQL_PASSWORD: movie_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
